apiVersion: apps/v1
kind: Deployment
metadata:
  name: yash-ms3-deployment
spec:
  selector:
    matchLabels:
      app: yash-app3
  template:
    metadata:
      labels:
        app: yash-app3
    spec:
      containers:
      - name: ms3
        image: yashbbhatt/yash-ms2:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3003
